/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_matthiasfisch_mysticlight4j_api_MysticLightNativeBinding */

#ifndef _Included_de_matthiasfisch_mysticlight4j_api_MysticLightNativeBinding
#define _Included_de_matthiasfisch_mysticlight4j_api_MysticLightNativeBinding
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_matthiasfisch_mysticlight4j_api_MysticLightNativeBinding
 * Method:    isProcessElevated
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_matthiasfisch_mysticlight4j_api_MysticLightNativeBinding_isProcessElevated
  (JNIEnv *, jclass);

/*
 * Class:     de_matthiasfisch_mysticlight4j_api_MysticLightNativeBinding
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_matthiasfisch_mysticlight4j_api_MysticLightNativeBinding_initialize
  (JNIEnv *, jclass);

/*
 * Class:     de_matthiasfisch_mysticlight4j_api_MysticLightNativeBinding
 * Method:    getDeviceInfo
 * Signature: ()[Lde/matthiasfisch/mysticlight4j/api/DeviceInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_de_matthiasfisch_mysticlight4j_api_MysticLightNativeBinding_getDeviceInfo
  (JNIEnv *, jclass);

/*
 * Class:     de_matthiasfisch_mysticlight4j_api_MysticLightNativeBinding
 * Method:    getDeviceName
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_de_matthiasfisch_mysticlight4j_api_MysticLightNativeBinding_getDeviceName
  (JNIEnv *, jclass, jstring);

/*
 * Class:     de_matthiasfisch_mysticlight4j_api_MysticLightNativeBinding
 * Method:    getDeviceNameEx
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_matthiasfisch_mysticlight4j_api_MysticLightNativeBinding_getDeviceNameEx
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     de_matthiasfisch_mysticlight4j_api_MysticLightNativeBinding
 * Method:    getLedInfo
 * Signature: (Ljava/lang/String;I)Lde/matthiasfisch/mysticlight4j/api/LedInfo;
 */
JNIEXPORT jobject JNICALL Java_de_matthiasfisch_mysticlight4j_api_MysticLightNativeBinding_getLedInfo
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     de_matthiasfisch_mysticlight4j_api_MysticLightNativeBinding
 * Method:    getLedName
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_de_matthiasfisch_mysticlight4j_api_MysticLightNativeBinding_getLedName
  (JNIEnv *, jclass, jstring);

/*
 * Class:     de_matthiasfisch_mysticlight4j_api_MysticLightNativeBinding
 * Method:    getLedColor
 * Signature: (Ljava/lang/String;I)Lde/matthiasfisch/mysticlight4j/api/Color;
 */
JNIEXPORT jobject JNICALL Java_de_matthiasfisch_mysticlight4j_api_MysticLightNativeBinding_getLedColor
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     de_matthiasfisch_mysticlight4j_api_MysticLightNativeBinding
 * Method:    getLedStyle
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_matthiasfisch_mysticlight4j_api_MysticLightNativeBinding_getLedStyle
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     de_matthiasfisch_mysticlight4j_api_MysticLightNativeBinding
 * Method:    getLedMaxBright
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_de_matthiasfisch_mysticlight4j_api_MysticLightNativeBinding_getLedMaxBright
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     de_matthiasfisch_mysticlight4j_api_MysticLightNativeBinding
 * Method:    getLedBright
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_de_matthiasfisch_mysticlight4j_api_MysticLightNativeBinding_getLedBright
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     de_matthiasfisch_mysticlight4j_api_MysticLightNativeBinding
 * Method:    getLedMaxSpeed
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_de_matthiasfisch_mysticlight4j_api_MysticLightNativeBinding_getLedMaxSpeed
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     de_matthiasfisch_mysticlight4j_api_MysticLightNativeBinding
 * Method:    getLedSpeed
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_de_matthiasfisch_mysticlight4j_api_MysticLightNativeBinding_getLedSpeed
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     de_matthiasfisch_mysticlight4j_api_MysticLightNativeBinding
 * Method:    setLedColor
 * Signature: (Ljava/lang/String;ILde/matthiasfisch/mysticlight4j/api/Color;)V
 */
JNIEXPORT void JNICALL Java_de_matthiasfisch_mysticlight4j_api_MysticLightNativeBinding_setLedColor
  (JNIEnv *, jclass, jstring, jint, jobject);

/*
 * Class:     de_matthiasfisch_mysticlight4j_api_MysticLightNativeBinding
 * Method:    setLedColors
 * Signature: (Ljava/lang/String;I[Ljava/lang/String;Lde/matthiasfisch/mysticlight4j/api/Color;)V
 */
JNIEXPORT void JNICALL Java_de_matthiasfisch_mysticlight4j_api_MysticLightNativeBinding_setLedColors
  (JNIEnv *, jclass, jstring, jint, jobjectArray, jobject);

/*
 * Class:     de_matthiasfisch_mysticlight4j_api_MysticLightNativeBinding
 * Method:    setLedColorEx
 * Signature: (Ljava/lang/String;ILjava/lang/String;Lde/matthiasfisch/mysticlight4j/api/Color;Z)V
 */
JNIEXPORT void JNICALL Java_de_matthiasfisch_mysticlight4j_api_MysticLightNativeBinding_setLedColorEx
  (JNIEnv *, jclass, jstring, jint, jstring, jobject, jboolean);

/*
 * Class:     de_matthiasfisch_mysticlight4j_api_MysticLightNativeBinding
 * Method:    setLedColorSync
 * Signature: (Ljava/lang/String;ILjava/lang/String;Lde/matthiasfisch/mysticlight4j/api/Color;Z)V
 */
JNIEXPORT void JNICALL Java_de_matthiasfisch_mysticlight4j_api_MysticLightNativeBinding_setLedColorSync
  (JNIEnv *, jclass, jstring, jint, jstring, jobject, jboolean);

/*
 * Class:     de_matthiasfisch_mysticlight4j_api_MysticLightNativeBinding
 * Method:    setLedStyle
 * Signature: (Ljava/lang/String;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_matthiasfisch_mysticlight4j_api_MysticLightNativeBinding_setLedStyle
  (JNIEnv *, jclass, jstring, jint, jstring);

/*
 * Class:     de_matthiasfisch_mysticlight4j_api_MysticLightNativeBinding
 * Method:    setLedBright
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_de_matthiasfisch_mysticlight4j_api_MysticLightNativeBinding_setLedBright
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     de_matthiasfisch_mysticlight4j_api_MysticLightNativeBinding
 * Method:    setLedSpeed
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_de_matthiasfisch_mysticlight4j_api_MysticLightNativeBinding_setLedSpeed
  (JNIEnv *, jclass, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
